### ISSUE TITLE
Keep getting asked for permissions

### ISSUE THREAD

**Issue by itainoam** [surrealroad/alfred-reminders#63] opened 2017-10-31 08:52 UTC
Thanks for the great workflow!

I run into problems where it keeps asking me for permissions. It does that multiple times per task (like 8) and regardless if I restarted Alfred or not.

![screen1](https://user-images.githubusercontent.com/12605830/32215058-83a66efa-be29-11e7-9614-1be38c251d73.png)

**Comment by nampdn** [comment] 2017-11-08 08:15
same here, is there any work around yet?

**Comment by surrealroad** [comment] 2017-11-08 10:22
It seems this must be an issue with macOS itself or Alfred, there's nothing the workflow does to explicitly request access to reminders. That said it would be helpful to know if everyone who has this issue:
- Has a specific version of macOS
- Has only just installed the workflow or has been using it for a while

**Comment by itainoam** [comment] 2017-11-22 14:39
* Just installed
* Version: 10.12.6

**Comment by mickey4322** [comment] 2018-02-08 15:45
Same issue. I keep getting requests for reminders multiple times after typing "r" on alfred (in Preferences> Security & Privacy, access is enabled). And also for Contacts, every time the mac boots or alfred is restarted.
Mac OS 10.13.3
Alfred Ver. 3.5.1 (833)
Alfred-reminders ver. 74

**Comment by peginatta** [comment] 2018-02-09 03:13
same here; high sierra, 
Have been using it for a month already

**Comment by AleksIralda** [comment] 2018-02-25 17:07
Same here, Mac OS 10.13.3
Alfred Ver. 3.6

**Comment by surrealroad** [comment] 2018-02-25 18:52
dupe of #53

**Closed by surrealroad** 2018-02-25 18:52 UTC
