### ISSUE TITLE
Is it possible to have tasks for today to be created as all day task (without a time)?

### ISSUE THREAD

**Issue by joshdoyle** [surrealroad/alfred-reminders#100] opened 2021-04-15 14:38 UTC
I'd like to enter all-day tasks using "r Take out the trash today" and not have it assign a time. Currently, it defaults to noon. Where can I edit the script to make this change?

**Comment by surrealroad** [comment] 2024-10-15 08:39
dupe of #124

**Closed by surrealroad** 2024-10-15 08:39 UTC
