### ISSUE TITLE
Show default list current unfinished task

### ISSUE THREAD

**Issue by fabiozc** [surrealroad/alfred-reminders#64] opened 2017-11-05 13:01 UTC
Would be great to could check which task stills opened typing "r list" or "r ls" something like that. Is it possible?

Thank you for this amazing workflow!

**Comment by surrealroad** [comment] 2017-11-05 15:09
Sorry, no longer possible due to an apple bug.

Dupe of #2

**Closed by surrealroad** 2017-11-05 15:09 UTC
